-- ====================================================================================
-- DUMP DATABASE JURNAL MENGAJAR (SCHEMA & MASTER DATA)
-- ====================================================================================

-- --------------------------------------------------------
-- 1. TABEL UTAMA & MASTER DATA
-- --------------------------------------------------------

-- Tabel Profiles (Sinkron dengan auth.users)
CREATE TABLE public.profiles (
    id uuid NOT NULL PRIMARY KEY,
    email text,
    nama_lengkap text,
    role text CHECK (role IN ('admin', 'guru')),
    jabatan text,
    alamat text,
    no_telp text,
    foto_url text
);

-- Master Kelas
CREATE TABLE public.master_kelas (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nama_kelas text NOT NULL UNIQUE
);

-- Master Mata Pelajaran
CREATE TABLE public.master_mata_pelajaran (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nama_mata_pelajaran text NOT NULL UNIQUE,
    created_at timestamp with time zone DEFAULT now()
);

-- Master Periode Ajaran
CREATE TABLE public.master_periode (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nama_periode text NOT NULL,
    is_active boolean DEFAULT false
);

-- Master Jam / Waktu Pelajaran
CREATE TABLE public.master_jam (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    jam_ke integer NOT NULL UNIQUE,
    waktu_reguler text NOT NULL,
    waktu_puasa text NOT NULL,
    created_at timestamp with time zone DEFAULT now()
);

-- Master Siswa
CREATE TABLE public.master_siswa (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nama_siswa text NOT NULL,
    nisn text UNIQUE,
    kelas_id bigint NOT NULL REFERENCES public.master_kelas(id) ON DELETE CASCADE
);

-- --------------------------------------------------------
-- 2. TABEL TRANSAKSIONAL
-- --------------------------------------------------------

-- Jadwal Mengajar
CREATE TABLE public.jadwal_mengajar (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    guru_id uuid REFERENCES public.profiles(id) ON DELETE CASCADE,
    periode_id bigint REFERENCES public.master_periode(id) ON DELETE CASCADE,
    kelas_id bigint REFERENCES public.master_kelas(id) ON DELETE CASCADE,
    mata_pelajaran_id bigint REFERENCES public.master_mata_pelajaran(id) ON DELETE CASCADE,
    jam_id bigint REFERENCES public.master_jam(id) ON DELETE CASCADE,
    hari integer CHECK (hari >= 1 AND hari <= 7), -- Calculated via trigger
    tanggal date,
    is_active boolean DEFAULT true
);

-- Jurnal Harian
CREATE TABLE public.jurnal_harian (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    jadwal_id bigint NOT NULL REFERENCES public.jadwal_mengajar(id) ON DELETE CASCADE,
    tanggal date DEFAULT CURRENT_DATE,
    materi text NOT NULL,
    catatan text,
    foto_lampiran_url text,
    is_telat boolean DEFAULT false,
    status text DEFAULT 'pending' CHECK (status IN ('pending', 'approved', 'rejected')),
    catatan_admin text,
    validated_by uuid REFERENCES public.profiles(id),
    validated_at timestamp with time zone,
    created_at timestamp with time zone DEFAULT now()
);

-- Presensi Siswa
CREATE TABLE public.presensi_siswa (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    jurnal_id bigint NOT NULL REFERENCES public.jurnal_harian(id) ON DELETE CASCADE,
    siswa_id bigint NOT NULL REFERENCES public.master_siswa(id) ON DELETE CASCADE,
    kelas_id bigint REFERENCES public.master_kelas(id),
    status text DEFAULT 'Hadir' CHECK (status IN ('Hadir', 'Sakit', 'Izin', 'Alpha', 'H', 'S', 'I', 'A'))
);

-- --------------------------------------------------------
-- 3. KONFIGURASI KEAMANAN (RLS & POLICIES)
-- --------------------------------------------------------

-- Enable RLS on all tables
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.master_kelas ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.master_mata_pelajaran ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.master_periode ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.master_jam ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.master_siswa ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.jadwal_mengajar ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.jurnal_harian ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.presensi_siswa ENABLE ROW LEVEL SECURITY;

-- Apply Public Full Access Policies
DO $$ 
DECLARE 
    r RECORD;
BEGIN 
    FOR r IN (SELECT tablename FROM pg_tables WHERE schemaname = 'public') LOOP 
        EXECUTE format('DROP POLICY IF EXISTS "Public Full Access" ON public.%I', r.tablename);
        EXECUTE format('CREATE POLICY "Public Full Access" ON public.%I FOR ALL USING (true) WITH CHECK (true)', r.tablename);
    END LOOP; 
END $$;

-- --------------------------------------------------------
-- 4. TRIGGERS
-- --------------------------------------------------------

-- Sync Profiles from Auth
CREATE OR REPLACE FUNCTION public.handle_sync_profile_email()
RETURNS TRIGGER AS $$
BEGIN
    IF (TG_OP = 'INSERT') THEN
        INSERT INTO public.profiles (id, email) VALUES (NEW.id, NEW.email);
    ELSIF (TG_OP = 'UPDATE') THEN
        UPDATE public.profiles SET email = NEW.email WHERE id = NEW.id;
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE TRIGGER on_auth_user_created
  AFTER INSERT OR UPDATE OF email ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_sync_profile_email();

-- Set Hari from Date
CREATE OR REPLACE FUNCTION public.set_hari_dari_tanggal()
RETURNS TRIGGER AS $$
BEGIN
   IF NEW.tanggal IS NOT NULL THEN NEW.hari := EXTRACT(ISODOW FROM NEW.tanggal); END IF;
   RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_jadwal_set_hari
  BEFORE INSERT OR UPDATE ON public.jadwal_mengajar
  FOR EACH ROW EXECUTE FUNCTION public.set_hari_dari_tanggal();

-- Set Is Telat (> 3 days)
CREATE OR REPLACE FUNCTION public.set_is_telat_jurnal()
RETURNS TRIGGER AS $$
BEGIN
   NEW.is_telat := (CURRENT_DATE - NEW.tanggal) > 3;
   RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_jurnal_set_telat
  BEFORE INSERT ON public.jurnal_harian
  FOR EACH ROW EXECUTE FUNCTION public.set_is_telat_jurnal();

-- --------------------------------------------------------
-- 5. SEEDING MASTER DATA (REAL DATA PATTERN)
-- --------------------------------------------------------

-- Master Kelas
INSERT INTO public.master_kelas (nama_kelas) VALUES
('X RPL 1'), ('X RPL 2'), ('XI RPL 1'), ('XI RPL 2'), ('XII RPL 1');

-- Master Mata Pelajaran
INSERT INTO public.master_mata_pelajaran (nama_mata_pelajaran) VALUES
('Pemrograman Web'), ('Basis Data'), ('Pemrograman Berbasis Objek'), ('Matematika'), 
('Bahasa Indonesia'), ('Bahasa Inggris'), ('PAI'), ('PPKn'), ('Sejarah'), ('Seni Budaya'), 
('PJOK'), ('Desain Grafis'), ('Pemrograman Dasar'), ('Sistem Komputer'), ('PKK');

-- Master Periode
INSERT INTO public.master_periode (nama_periode, is_active) VALUES
('2025/2026 Ganjil', false), ('2025/2026 Genap', true);

-- Master Jam
INSERT INTO public.master_jam (jam_ke, waktu_reguler, waktu_puasa) VALUES
(1, '07.00-07.50', '07.30-08.05'), (2, '07.50-08.40', '08.05-08.40'),
(3, '08.45-09.35', '08.45-09.20'), (4, '09.35-10.25', '09.20-09.55'),
(5, '10.30-11.20', '10.00-10.35'), (6, '11.20-12.10', '10.35-11.10'),
(7, '13.10-14.00', '11.10-11.45'), (8, '14.00-14.50', '13.00-13.35'),
(9, '14.55-15.45', '13.35-14.10'), (10, '15.45-16.35', '14.10-14.45'),
(11, '18.15-19.05', '15.15-15.45'), (12, '19.05-19.55', '15.45-16.15');

-- Note: Master Siswa (180 data) and Transactional Data (Profiles/Jadwal) 
-- are not included here as they are managed via application or external seeding.

-- ====================================================================================
-- END OF SCRIPT
-- ====================================================================================
